// packages/docs-next/src/examples/react/ListboxBasic.tsx
import { useState } from "react";
import { Listbox } from "@libretexts/davis-react";

const FRAMEWORKS = ["React", "Vue", "Angular", "Svelte", "Solid"];

export default function ListboxBasic() {
  const [value, setValue] = useState<string | null>(null);
  return (
    <div className="w-64">
      <Listbox value={value} onChange={setValue}>
        <Listbox.Label>Framework</Listbox.Label>
        <Listbox.Button placeholder="Select a framework…" />
        <Listbox.Options>
          {FRAMEWORKS.map((f) => (
            <Listbox.Option key={f} value={f}>
              {f}
            </Listbox.Option>
          ))}
        </Listbox.Options>
      </Listbox>
    </div>
  );
}

// packages/docs-next/src/examples/vue/ListboxBasic.vue
<script setup lang="ts">
import { ref } from "vue";
import {
  Listbox,
  ListboxLabel,
  ListboxButton,
  ListboxOptions,
  ListboxOption,
} from "@libretexts/davis-vue";

const FRAMEWORKS = ["React", "Vue", "Angular", "Svelte", "Solid"];
const selected = ref<string | null>(null);
</script>

<template>
  <div class="w-64">
    <Listbox v-model="selected">
      <ListboxLabel>Framework</ListboxLabel>
      <ListboxButton placeholder="Select a framework…" />
      <ListboxOptions>
        <ListboxOption v-for="f in FRAMEWORKS" :key="f" :value="f">
          {{ f }}
        </ListboxOption>
      </ListboxOptions>
    </Listbox>
  </div>
</template>
