// packages/docs-next/src/examples/vue/ButtonVariants.vue
<script setup lang="ts">
import { Button } from "@libretexts/davis-vue";
</script>

<template>
  <Button variant="primary">Primary</Button>
  <Button variant="secondary">Secondary</Button>
  <Button variant="tertiary">Tertiary</Button>
  <Button variant="destructive">Destructive</Button>
  <Button variant="ghost">Ghost</Button>
  <Button variant="outline">Outline</Button>
</template>

// packages/docs-next/src/examples/react/ButtonVariants.tsx
import { Button } from "@libretexts/davis-react";

export default function ButtonVariants() {
  return (
    <>
      <Button variant="primary">Primary</Button>
      <Button variant="secondary">Secondary</Button>
      <Button variant="tertiary">Tertiary</Button>
      <Button variant="destructive">Destructive</Button>
      <Button variant="ghost">Ghost</Button>
      <Button variant="outline">Outline</Button>
    </>
  );
}
