// packages/docs-next/src/examples/vue/FormSectionBasic.vue
<script setup lang="ts">
import { FormSection, Input } from "@libretexts/davis-vue";
</script>

<template>
  <FormSection title="Personal Information" description="Tell us a bit about yourself.">
    <Input name="first-name" label="First name" />
    <Input name="last-name" label="Last name" />
    <Input name="email" label="Email address" type="email" />
  </FormSection>
</template>

// packages/docs-next/src/examples/react/FormSectionBasic.tsx
import { FormSection, Input } from "@libretexts/davis-react";

export default function FormSectionBasic() {
  return (
    <FormSection
      title="Personal Information"
      description="Tell us a bit about yourself."
    >
      <Input name="first-name" label="First name" />
      <Input name="last-name" label="Last name" />
      <Input name="email" label="Email address" type="email" />
    </FormSection>
  );
}
