// packages/docs-next/src/examples/vue/SelectBasic.vue
<script setup lang="ts">
import { Select } from "@libretexts/davis-vue";

const options = [
  { value: "us", label: "United States" },
  { value: "ca", label: "Canada" },
  { value: "mx", label: "Mexico" },
  { value: "uk", label: "United Kingdom" },
];
</script>

<template>
  <Select
    name="country"
    label="Country"
    placeholder="Select a country"
    :options="options"
  />
</template>

// packages/docs-next/src/examples/react/SelectBasic.tsx
import { Select } from "@libretexts/davis-react";

const options = [
  { value: "us", label: "United States" },
  { value: "ca", label: "Canada" },
  { value: "mx", label: "Mexico" },
  { value: "uk", label: "United Kingdom" },
];

export default function SelectBasic() {
  return (
    <Select
      name="country"
      label="Country"
      placeholder="Select a country"
      options={options}
    />
  );
}
