// packages/vue/src/components/InputGroup.vue
<script lang="ts">
export type InputGroupSize = "sm" | "md" | "lg";
</script>

<script setup lang="ts">
import clsx from "clsx";
import { inputGroup as inputGroupVariants } from "@libretexts/davis-core";

const props = withDefaults(
  defineProps<{
    size?: InputGroupSize;
    class?: string;
  }>(),
  {
    size: "md",
  }
);

const { root, addon, prefix: prefixClass, suffix: suffixClass, inputSlot, inputFirst, inputLast } = inputGroupVariants({ size: props.size });
</script>

<template>
  <div :class="clsx(root(), 'items-end', props.class)">
    <span v-if="$slots.prefix" :class="clsx(addon(), prefixClass())">
      <slot name="prefix" />
    </span>
    <div :class="clsx(inputSlot(), $slots.prefix && inputFirst(), $slots.suffix && inputLast())">
      <slot />
    </div>
    <span v-if="$slots.suffix" :class="clsx(addon(), suffixClass())">
      <slot name="suffix" />
    </span>
  </div>
</template>

// packages/react/src/components/input-group.tsx
import clsx from "clsx";
import { type ReactNode } from "react";
import { inputGroup as inputGroupVariants } from "@libretexts/davis-core";

export type InputGroupSize = "sm" | "md" | "lg";

export type InputGroupProps = {
  prefix?: ReactNode;
  suffix?: ReactNode;
  children: ReactNode;
  size?: InputGroupSize;
  className?: string;
};

export function InputGroup({ prefix, suffix, children, size = "md", className }: InputGroupProps) {
  const { root, addon, prefix: prefixClass, suffix: suffixClass, inputSlot, inputFirst, inputLast } = inputGroupVariants({ size });
  return (
    <div className={clsx(root(), "items-end", className)}>
      {prefix && (
        <span className={clsx(addon(), prefixClass())}>{prefix}</span>
      )}
      <div className={clsx(inputSlot(), prefix && inputFirst(), suffix && inputLast())}>
        {children}
      </div>
      {suffix && (
        <span className={clsx(addon(), suffixClass())}>{suffix}</span>
      )}
    </div>
  );
}

InputGroup.displayName = "InputGroup";
