// packages/vue/src/components/Radio.vue
<script setup lang="ts">
import { computed, inject } from "vue";
import clsx from "clsx";
import { RadioGroupContextKey } from "./RadioGroup.vue";

type RadioSize = "sm" | "md" | "lg";

const props = withDefaults(
  defineProps<{
    value: string;
    label?: string;
    description?: string;
    disabled?: boolean;
    error?: boolean;
    size?: RadioSize;
    class?: string;
    labelClass?: string;
  }>(),
  {
    disabled: false,
    error: false,
    size: "md",
  }
);

const context = inject(RadioGroupContextKey, null);

const sizeClasses: Record<RadioSize, string> = {
  sm: "size-3.5",
  md: "size-4",
  lg: "size-5",
};

const dotSize: Record<RadioSize, string> = {
  sm: "size-1.5",
  md: "size-2",
  lg: "size-2.5",
};

const isChecked = computed(() => context?.modelValue.value === props.value);
const isDisabled = computed(() => props.disabled || (context?.disabled.value ?? false));

function handleChange() {
  if (!isDisabled.value) {
    context?.onChange(props.value);
  }
}
</script>

<template>
  <div
    :class="clsx(
      'flex gap-x-3 cursor-pointer',
      isDisabled && 'opacity-50 cursor-not-allowed',
      props.class
    )"
    role="radio"
    :aria-checked="isChecked"
    :aria-disabled="isDisabled"
    tabindex="0"
    @click="handleChange"
    @keydown.space.prevent="handleChange"
    @keydown.enter.prevent="handleChange"
  >
    <div class="flex shrink-0 items-center h-6">
      <div :class="clsx('grid grid-cols-1 place-items-center', sizeClasses[props.size])">
        <span
          :class="clsx(
            'col-start-1 row-start-1 rounded-full border',
            sizeClasses[props.size],
            isDisabled
              ? 'border-gray-300 bg-gray-100'
              : props.error
                ? 'border-red-500 bg-red-100'
                : isChecked
                  ? 'border-primary bg-primary'
                  : 'border-gray-300 bg-white'
          )"
        />
        <span
          :class="clsx(
            'col-start-1 row-start-1 rounded-full bg-white',
            !isChecked && 'opacity-0',
            isDisabled && 'bg-gray-400',
            dotSize[props.size]
          )"
        />
      </div>
    </div>
    <div v-if="props.label || props.description" class="text-sm/6">
      <span
        v-if="props.label"
        :class="clsx(
          'font-medium text-gray-700',
          props.error && 'text-red-600',
          isDisabled && 'opacity-50',
          props.labelClass
        )"
      >
        {{ props.label }}
      </span>
      <p v-if="props.description" :class="clsx('text-gray-500', isDisabled && 'opacity-50')">
        {{ props.description }}
      </p>
    </div>
  </div>
</template>

// packages/react/src/components/radio.tsx
import { Radio as HeadlessRadio } from "@headlessui/react";
import clsx from "clsx";

type RadioVariants = {
  variant?: "default" | "error";
  size?: "sm" | "md" | "lg";
};

export type RadioProps = RadioVariants & {
  value: string;
  label?: string;
  className?: string;
  labelClassName?: string;
  disabled?: boolean;
  error?: boolean;
  /** Description text displayed below the label */
  description?: string;
};

export function Radio({
  value,
  label,
  className,
  labelClassName,
  disabled = false,
  error = false,
  size = "md",
  description,
}: RadioProps) {
  const sizeClasses = {
    sm: "size-3.5",
    md: "size-4",
    lg: "size-5",
  };

  const dotSize = {
    sm: "size-1.5",
    md: "size-2",
    lg: "size-2.5",
  };

  return (
    <HeadlessRadio
      value={value}
      disabled={disabled}
      className={clsx(
        "group flex gap-x-3 cursor-pointer",
        "data-[disabled]:cursor-not-allowed data-[disabled]:opacity-50",
        className
      )}
    >
      <div className="flex shrink-0 items-center h-6">
        <div
          className={clsx(
            "grid grid-cols-1 place-items-center",
            sizeClasses[size]
          )}
        >
          <span
            className={clsx(
              "col-start-1 row-start-1 rounded-full border border-gray-300 bg-white",
              "group-data-[checked]:border-primary group-data-[checked]:bg-primary",
              "group-data-[disabled]:border-gray-300 group-data-[disabled]:bg-gray-100",
              sizeClasses[size],
              error && "!border-red-500 !bg-red-100"
            )}
          />
          {/* Inner dot for selected state */}
          <span
            className={clsx(
              "col-start-1 row-start-1 rounded-full bg-white",
              "opacity-0 group-data-[checked]:opacity-100",
              "group-data-[disabled]:bg-gray-400",
              dotSize[size]
            )}
          />
        </div>
      </div>
      {(label || description) && (
        <div className="text-sm/6">
          {label && (
            <span
              className={clsx(
                "font-medium text-gray-700",
                error && "text-red-600",
                "group-data-[disabled]:opacity-50",
                labelClassName
              )}
            >
              {label}
            </span>
          )}
          {description && (
            <p
              className={clsx(
                "text-gray-500",
                "group-data-[disabled]:opacity-50"
              )}
            >
              {description}
            </p>
          )}
        </div>
      )}
    </HeadlessRadio>
  );
}

Radio.displayName = "Radio";
