// packages/vue/src/components/Skeleton.vue
<script lang="ts">
export type SkeletonVariant = "text" | "circular" | "rectangular" | "rounded";
</script>

<script setup lang="ts">
import { computed } from "vue";
import clsx from "clsx";
import { skeleton } from "@libretexts/davis-core";

const props = withDefaults(
  defineProps<{
    variant?: SkeletonVariant;
    width?: string | number;
    height?: string | number;
    lines?: number;
    ariaLabel?: string;
    class?: string;
  }>(),
  {
    variant: "rounded",
    ariaLabel: "Loading...",
  }
);

const style = computed(() => ({
  width: typeof props.width === "number" ? `${props.width}px` : props.width,
  height: typeof props.height === "number" ? `${props.height}px` : props.height,
}));

const showMultipleLines = computed(() => props.variant === "text" && props.lines && props.lines > 1);
</script>

<template>
  <div
    v-if="showMultipleLines"
    role="status"
    :aria-label="props.ariaLabel"
    :class="clsx('flex flex-col gap-2', props.class)"
  >
    <div
      v-for="i in props.lines"
      :key="i"
      :class="clsx(
        skeleton({ variant: 'text' }),
        i === props.lines && 'w-3/4'
      )"
    />
  </div>
  <div
    v-else
    role="status"
    :aria-label="props.ariaLabel"
    :style="style"
    :class="clsx(skeleton({ variant: props.variant }), props.class)"
  />
</template>

// packages/react/src/components/skeleton.tsx
import clsx from "clsx";
import { forwardRef, type HTMLAttributes } from "react";
import { skeleton } from "@libretexts/davis-core";

export type SkeletonVariant = "text" | "circular" | "rectangular" | "rounded";

export type SkeletonProps = {
  variant?: SkeletonVariant;
  width?: string | number;
  height?: string | number;
  lines?: number;
  className?: string;
} & Omit<HTMLAttributes<HTMLDivElement>, "children">;

export const Skeleton = forwardRef<HTMLDivElement, SkeletonProps>(
  (
    {
      variant = "rounded",
      width,
      height,
      lines,
      className,
      "aria-label": ariaLabel = "Loading...",
      ...props
    },
    ref
  ) => {
    const style: React.CSSProperties = {
      width: typeof width === "number" ? `${width}px` : width,
      height: typeof height === "number" ? `${height}px` : height,
    };

    if (variant === "text" && lines && lines > 1) {
      return (
        <div ref={ref} role="status" aria-label={ariaLabel} className={clsx("flex flex-col gap-2", className)} {...props}>
          {Array.from({ length: lines }).map((_, i) => (
            <div
              key={i}
              className={clsx(
                skeleton({ variant: "text" }),
                i === lines - 1 && "w-3/4"
              )}
            />
          ))}
        </div>
      );
    }

    return (
      <div
        ref={ref}
        role="status"
        aria-label={ariaLabel}
        style={style}
        className={clsx(skeleton({ variant }), className)}
        {...props}
      />
    );
  }
);

Skeleton.displayName = "Skeleton";
