// packages/vue/src/components/SkipLink.vue
<script setup lang="ts">
import clsx from "clsx";
import { skipLink as skipLinkVariants } from "@libretexts/davis-core";

const props = withDefaults(
  defineProps<{
    targetId?: string;
    class?: string;
  }>(),
  {
    targetId: "main-content",
  }
);
</script>

<template>
  <a :href="`#${props.targetId}`" :class="clsx(skipLinkVariants(), props.class)">
    <slot>Skip to main content</slot>
  </a>
</template>

// packages/react/src/components/skip-link.tsx
import { type ReactNode } from "react";
import { skipLink as skipLinkVariants } from "@libretexts/davis-core";
import clsx from "clsx";

export type SkipLinkProps = {
  /** ID of the target element to skip to (default: "main-content") */
  targetId?: string;
  /** Link text (default: "Skip to main content") */
  children?: ReactNode;
  /** Additional class names */
  className?: string;
};

export function SkipLink({
  targetId = "main-content",
  children = "Skip to main content",
  className,
}: SkipLinkProps) {
  return (
    <a href={`#${targetId}`} className={clsx(skipLinkVariants(), className)}>
      {children}
    </a>
  );
}

SkipLink.displayName = "SkipLink";
