// packages/vue/src/components/Textarea.vue
<script setup lang="ts">
import { computed } from "vue";
import clsx from "clsx";
import { textarea } from "@libretexts/davis-core";

type TextareaVariant = "default" | "error";
type TextareaSize = "sm" | "md" | "lg";

const props = withDefaults(
  defineProps<{
    name: string;
    label: string;
    modelValue?: string;
    variant?: TextareaVariant;
    size?: TextareaSize;
    rows?: number;
    error?: boolean;
    required?: boolean;
    disabled?: boolean;
    helperText?: string;
    errorMessage?: string;
    placeholder?: string;
    class?: string;
    labelClass?: string;
    textareaClass?: string;
  }>(),
  {
    variant: "default",
    size: "md",
    rows: 4,
    error: false,
    required: false,
    disabled: false,
  }
);

const emit = defineEmits<{
  "update:modelValue": [value: string];
}>();

const showError = computed(() => props.error && props.errorMessage);
const showHelper = computed(() => !showError.value && props.helperText);
const computedVariant = computed(() => props.error ? "error" : props.variant);
</script>

<template>
  <div :class="props.class">
    <label
      :for="props.name"
      :class="clsx(
        'block text-base/6 font-medium text-gray-700',
        props.labelClass
      )"
    >
      {{ props.label }}
      <span v-if="props.required" class="text-danger ml-0.5">*</span>
    </label>
    <div class="mt-1.5">
      <textarea
        :id="props.name"
        :name="props.name"
        :value="props.modelValue"
        :rows="props.rows"
        :aria-invalid="props.error ? 'true' : undefined"
        :aria-describedby="showError ? `${props.name}-error` : showHelper ? `${props.name}-helper` : undefined"
        :placeholder="props.placeholder || props.label"
        :disabled="props.disabled"
        :class="clsx(
          textarea({ variant: computedVariant, size: props.size }),
          props.textareaClass
        )"
        @input="emit('update:modelValue', ($event.target as HTMLTextAreaElement).value)"
      />
    </div>
    <p v-if="showError" :id="`${props.name}-error`" class="mt-1.5 text-sm text-danger">
      {{ props.errorMessage }}
    </p>
    <p v-if="showHelper" :id="`${props.name}-helper`" class="mt-1.5 text-sm text-gray-500">
      {{ props.helperText }}
    </p>
  </div>
</template>

// packages/react/src/components/textarea.tsx
import clsx from "clsx";
import {
  forwardRef,
  type TextareaHTMLAttributes,
  useEffect,
  useRef,
  useCallback,
} from "react";
import { textarea } from "@libretexts/davis-core";

type TextareaVariants = {
  variant?: "default" | "error";
  size?: "sm" | "md" | "lg";
};

export type TextareaProps = Omit<
  TextareaHTMLAttributes<HTMLTextAreaElement>,
  "size"
> &
  TextareaVariants & {
    name: string;
    label: string;
    className?: string;
    labelClassName?: string;
    textareaClassName?: string;
    error?: boolean;
    required?: boolean;
    helperText?: string;
    errorMessage?: string;
    autoResize?: boolean;
    showCharacterCount?: boolean;
    rows?: number;
  };

export const Textarea = forwardRef<HTMLTextAreaElement, TextareaProps>(
  (
    {
      className,
      label,
      name,
      labelClassName,
      textareaClassName,
      error,
      required,
      variant,
      size,
      helperText,
      errorMessage,
      autoResize = false,
      showCharacterCount = false,
      rows = 4,
      maxLength,
      defaultValue,
      onChange,
      ...props
    },
    ref
  ) => {
    const showError = error && errorMessage;
    const showHelper = !showError && helperText;
    const internalRef = useRef<HTMLTextAreaElement>(null);
    const textareaRef = (ref as React.RefObject<HTMLTextAreaElement>) || internalRef;

    const adjustHeight = useCallback(() => {
      const element = textareaRef.current;
      if (element && autoResize) {
        element.style.height = "auto";
        element.style.height = `${element.scrollHeight}px`;
      }
    }, [autoResize, textareaRef]);

    useEffect(() => {
      if (autoResize) {
        adjustHeight();
      }
    }, [autoResize, adjustHeight, defaultValue]);

    const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
      if (autoResize) {
        adjustHeight();
      }
      onChange?.(e);
    };

    const currentLength = textareaRef.current?.value.length ??
      (typeof defaultValue === "string" ? defaultValue.length : 0);

    return (
      <div className={clsx(className)}>
        <label
          htmlFor={name}
          className={clsx(
            "block text-base/6 font-medium text-gray-700",
            labelClassName
          )}
        >
          {label}
          {required && <span className="text-danger ml-0.5">*</span>}
        </label>
        <div className="mt-1.5">
          <textarea
            ref={textareaRef}
            id={name}
            name={name}
            rows={rows}
            maxLength={maxLength}
            defaultValue={defaultValue}
            aria-invalid={error ? "true" : undefined}
            aria-describedby={
              showError
                ? `${name}-error`
                : showHelper
                ? `${name}-helper`
                : undefined
            }
            placeholder={props.placeholder || label}
            onChange={handleChange}
            className={clsx(
              textarea({
                variant: error ? "error" : variant,
                size,
                autoResize,
              }),
              textareaClassName
            )}
            {...props}
          />
        </div>
        <div className="flex justify-between mt-1.5">
          <div>
            {showError && (
              <p id={`${name}-error`} className="text-sm text-danger">
                {errorMessage}
              </p>
            )}
            {showHelper && (
              <p id={`${name}-helper`} className="text-sm text-gray-500">
                {helperText}
              </p>
            )}
          </div>
          {showCharacterCount && maxLength && (
            <p className="text-sm text-gray-500">
              {currentLength}/{maxLength}
            </p>
          )}
        </div>
      </div>
    );
  }
);

Textarea.displayName = "Textarea";
