// packages/react/src/components/dialog.tsx
import {
  Dialog as HeadlessDialog,
  DialogBackdrop,
  DialogPanel,
  DialogTitle as HeadlessDialogTitle,
  DialogDescription as HeadlessDialogDescription,
} from "@headlessui/react";
import clsx from "clsx";
import { type ReactNode, createContext, useContext } from "react";
import { dialog as dialogVariants } from "@libretexts/davis-core";
import { useDavisContext } from "../context/davis-context";

type DialogContextValue = {
  onClose: () => void;
};

const DialogContext = createContext<DialogContextValue | null>(null);

function useDialogContext() {
  const ctx = useContext(DialogContext);
  if (!ctx) {
    throw new Error("Dialog subcomponents must be used within a Dialog");
  }
  return ctx;
}

export type DialogSize = "sm" | "md" | "lg" | "xl" | "full";

export type DialogProps = {
  open: boolean;
  onClose: (value: boolean) => void;
  children: ReactNode;
  size?: DialogSize;
  className?: string;
};

export function Dialog({
  open,
  onClose,
  children,
  size = "md",
  className,
}: DialogProps) {
  const { standalone } = useDavisContext();

  const dialogContent = (
    <HeadlessDialog open={open} onClose={onClose} className="relative z-50">
      <DialogBackdrop
        transition
        className={clsx(
          "fixed inset-0 bg-black/50",
          "transition duration-200 ease-out",
          "data-[closed]:opacity-0",
          "data-[enter]:opacity-100"
        )}
      />
      <div className="fixed inset-0 flex items-center justify-center overflow-y-auto p-4">
        <DialogPanel
          transition
          className={clsx(
            "transition duration-200 ease-out",
            "data-[closed]:opacity-0 data-[closed]:scale-95",
            "data-[enter]:opacity-100 data-[enter]:scale-100",
            dialogVariants({ size }),
            className
          )}
        >
          {children}
        </DialogPanel>
      </div>
    </HeadlessDialog>
  );

  return (
    <DialogContext.Provider value={{ onClose: () => onClose(false) }}>
      {standalone ? (
        <div className="davis">{dialogContent}</div>
      ) : (
        dialogContent
      )}
    </DialogContext.Provider>
  );
}

Dialog.displayName = "Dialog";

export type DialogHeaderProps = {
  children: ReactNode;
  className?: string;
};

function DialogHeader({ children, className }: DialogHeaderProps) {
  return (
    <div
      className={clsx(
        "flex items-center justify-between px-6 py-4 border-b border-gray-200",
        className
      )}
    >
      {children}
    </div>
  );
}

DialogHeader.displayName = "Dialog.Header";

export type DialogTitleProps = {
  children: ReactNode;
  className?: string;
};

function DialogTitle({ children, className }: DialogTitleProps) {
  return (
    <HeadlessDialogTitle
      className={clsx("text-lg font-semibold text-gray-900", className)}
    >
      {children}
    </HeadlessDialogTitle>
  );
}

DialogTitle.displayName = "Dialog.Title";

export type DialogDescriptionProps = {
  children: ReactNode;
  className?: string;
};

function DialogDescription({ children, className }: DialogDescriptionProps) {
  return (
    <HeadlessDialogDescription
      className={clsx("text-sm text-gray-500", className)}
    >
      {children}
    </HeadlessDialogDescription>
  );
}

DialogDescription.displayName = "Dialog.Description";

export type DialogFooterProps = {
  children: ReactNode;
  className?: string;
};

function DialogFooter({ children, className }: DialogFooterProps) {
  return (
    <div
      className={clsx(
        "flex items-center justify-end gap-3 px-6 py-4 border-t border-gray-200",
        className
      )}
    >
      {children}
    </div>
  );
}

DialogFooter.displayName = "Dialog.Footer";

export type DialogCloseProps = {
  className?: string;
  "aria-label"?: string;
};

function DialogClose({
  className,
  "aria-label": ariaLabel = "Close dialog",
}: DialogCloseProps) {
  const { onClose } = useDialogContext();
  return (
    <button
      type="button"
      onClick={onClose}
      aria-label={ariaLabel}
      className={clsx(
        "rounded-md p-1 text-gray-400 hover:text-gray-500 hover:bg-gray-100",
        "focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2",
        "transition-colors duration-150",
        className
      )}
    >
      <XMarkIcon className="size-5" aria-hidden="true" />
    </button>
  );
}

DialogClose.displayName = "Dialog.Close";

function XMarkIcon({ className }: { className?: string }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 20 20"
      fill="currentColor"
      className={className}
      aria-hidden="true"
    >
      <path d="M6.28 5.22a.75.75 0 0 0-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 1 0 1.06 1.06L10 11.06l3.72 3.72a.75.75 0 1 0 1.06-1.06L11.06 10l3.72-3.72a.75.75 0 0 0-1.06-1.06L10 8.94 6.28 5.22Z" />
    </svg>
  );
}

Dialog.Header = DialogHeader;
Dialog.Title = DialogTitle;
Dialog.Description = DialogDescription;
Dialog.Footer = DialogFooter;
Dialog.Close = DialogClose;

// packages/vue/src/components/Dialog.vue
<script lang="ts">
import type { InjectionKey } from "vue";

export type DialogSize = "sm" | "md" | "lg" | "xl" | "full";

type DialogContextValue = {
  close: () => void;
};

export const DialogContextKey: InjectionKey<DialogContextValue> = Symbol("DialogContext");
</script>

<script setup lang="ts">
import { provide } from "vue";
import {
  Dialog as HeadlessDialog,
  DialogPanel,
  TransitionRoot,
  TransitionChild,
} from "@headlessui/vue";
import clsx from "clsx";
import { dialog as dialogVariants } from "@libretexts/davis-core";

const props = withDefaults(
  defineProps<{
    open: boolean;
    size?: DialogSize;
    class?: string;
  }>(),
  {
    size: "md",
  }
);

const emit = defineEmits<{
  close: [value: boolean];
}>();

function handleClose() {
  emit("close", false);
}

provide(DialogContextKey, { close: handleClose });
</script>

<template>
  <TransitionRoot appear :show="props.open" as="template">
    <HeadlessDialog class="relative z-50" @close="handleClose">
      <TransitionChild
        as="template"
        enter="transition duration-200 ease-out"
        enter-from="opacity-0"
        enter-to="opacity-100"
        leave="transition duration-150 ease-in"
        leave-from="opacity-100"
        leave-to="opacity-0"
      >
        <div class="fixed inset-0 bg-black/50" aria-hidden="true" />
      </TransitionChild>

      <div class="fixed inset-0 flex items-center justify-center overflow-y-auto p-4">
        <TransitionChild
          as="template"
          enter="transition duration-200 ease-out"
          enter-from="opacity-0 scale-95"
          enter-to="opacity-100 scale-100"
          leave="transition duration-150 ease-in"
          leave-from="opacity-100 scale-100"
          leave-to="opacity-0 scale-95"
        >
          <DialogPanel
            :class="clsx(
              dialogVariants({ size: props.size }),
              props.class
            )"
          >
            <slot />
          </DialogPanel>
        </TransitionChild>
      </div>
    </HeadlessDialog>
  </TransitionRoot>
</template>
