// packages/react/src/components/divider.tsx
import clsx from "clsx";
import { forwardRef, type HTMLAttributes } from "react";
import { divider } from "@libretexts/davis-core";

export type DividerProps = {
  orientation?: "horizontal" | "vertical";
  label?: string;
  className?: string;
} & Omit<HTMLAttributes<HTMLElement>, "children">;

export const Divider = forwardRef<HTMLElement, DividerProps>(
  ({ orientation = "horizontal", label, className, ...props }, ref) => {
    const { root, line, label: labelClass } = divider({ orientation });

    if (label) {
      return (
        <div
          ref={ref as React.Ref<HTMLDivElement>}
          role="separator"
          aria-orientation={orientation}
          className={clsx(root(), className)}
          {...props}
        >
          <span aria-hidden="true" className={line()} />
          <span className={labelClass()}>{label}</span>
          <span aria-hidden="true" className={line()} />
        </div>
      );
    }

    if (orientation === "vertical") {
      return (
        <div
          ref={ref as React.Ref<HTMLDivElement>}
          role="separator"
          aria-orientation="vertical"
          className={clsx(root(), className)}
          {...props}
        >
          <span className={line()} />
        </div>
      );
    }

    return (
      <hr
        ref={ref as React.Ref<HTMLHRElement>}
        role="separator"
        className={clsx("border-gray-200 w-full", className)}
        {...props}
      />
    );
  }
);

Divider.displayName = "Divider";

// packages/vue/src/components/Divider.vue
<script setup lang="ts">
import clsx from "clsx";
import { divider } from "@libretexts/davis-core";

type DividerOrientation = "horizontal" | "vertical";

const props = withDefaults(
  defineProps<{
    orientation?: DividerOrientation;
    label?: string;
    class?: string;
  }>(),
  {
    orientation: "horizontal",
  }
);

const styles = divider({ orientation: props.orientation });
</script>

<template>
  <!-- With label -->
  <div
    v-if="props.label"
    role="separator"
    :aria-orientation="props.orientation"
    :class="clsx(styles.root(), props.class)"
  >
    <span aria-hidden="true" :class="styles.line()" />
    <span :class="styles.label()">{{ props.label }}</span>
    <span aria-hidden="true" :class="styles.line()" />
  </div>
  
  <!-- Vertical without label -->
  <div
    v-else-if="props.orientation === 'vertical'"
    role="separator"
    aria-orientation="vertical"
    :class="clsx(styles.root(), props.class)"
  >
    <span :class="styles.line()" />
  </div>
  
  <!-- Horizontal without label -->
  <hr
    v-else
    role="separator"
    :class="clsx('border-gray-200 w-full', props.class)"
  />
</template>
