// packages/react/src/components/form-section.tsx
import clsx from "clsx";
import { type ReactNode } from "react";
import { formSection as formSectionVariants } from "@libretexts/davis-core";

export type FormSectionProps = {
  title: string;
  description?: string;
  children: ReactNode;
  className?: string;
};

export function FormSection({ title, description, children, className }: FormSectionProps) {
  const { root, legend, description: descClass, content } = formSectionVariants();
  return (
    <fieldset className={clsx(root(), className)}>
      <legend className={clsx(legend(), "!px-0")}>{title}</legend>
      {description && <p className={descClass()}>{description}</p>}
      <div className={clsx(content(), "clear-both")}>{children}</div>
    </fieldset>
  );
}

FormSection.displayName = "FormSection";

// packages/vue/src/components/FormSection.vue
<script setup lang="ts">
import clsx from "clsx";
import { formSection as formSectionVariants } from "@libretexts/davis-core";

const props = defineProps<{
  title: string;
  description?: string;
  class?: string;
}>();

const { root, legend, description: descClass, content } = formSectionVariants();
</script>

<template>
  <fieldset :class="clsx(root(), props.class)">
    <legend :class="clsx(legend(), '!px-0')">{{ props.title }}</legend>
    <p v-if="props.description" :class="descClass()">{{ props.description }}</p>
    <div :class="clsx(content(), 'clear-both')">
      <slot />
    </div>
  </fieldset>
</template>
